HW02: implementing unpack string
ErmakGit/otus-hws pull request #2
Opened 2023-12-13 14:48 UTC by ErmakGit

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-12-13 18:41 UTC, vladislavmass requested changes
Хорошее начало. Код проходит все тесты с однобайтовой кодировкой. Но код не работает с многобайтовой кодировкой. Например не проходят следующие тест кейсы
1){input: "aaб0b", expected: "aab"},
2){input: "aaб2b", expected: "aaббb"},
Также есть проблемы обработкой слэша
1)`qwe\` должна быть ошибка так как слэш ничего не экранирует
2)`qwe\e` должна быть ошибка так как экранируются только цифры и слэш

2023-12-13 18:41 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +		if count, err := strconv.Atoi(string(input[ind+1])); err == nil {
Когда к строке  идет обращение по индексу то адресуется не символ, а конкретный байт.

2024-01-14 12:06 UTC, ErmakGit commented on hw02_unpack_string/unpack.go
> +		if count, err := strconv.Atoi(string(input[ind+1])); err == nil {
Fixed

2024-01-14 12:06 UTC, ErmakGit commented on hw02_unpack_string/unpack.go
> +		if count, err := strconv.Atoi(string(input[ind+1])); err == nil {
Fixed

2024-01-14 12:16 UTC, vladislavmass requested changes
Работа стала лучше, но некоторые правки привели к тому, что теперь не проходит тест кейс {input: `qwe\\`, expected: `qwe\`},

2024-01-14 18:22 UTC, vladislavmass approved these changes
Хорошая работа. Принято

2024-01-15 00:25 UTC, merged