Hw04 lru cache
ErmakGit/otus-hws pull request #4
Opened 2024-03-28 06:10 UTC by ErmakGit

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-03-30 05:36 UTC, vladislavmass requested changes

2024-03-30 05:36 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	items     map[*ListItem]*ListItem
Эта структура тут не нужна. Она только повышает расход оперативной памяти.

2024-03-30 05:36 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	once      sync.Once
once тут тоже не нужен

2024-03-30 05:36 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	items     map[*ListItem]*ListItem
Для подсчета длины списка вполне себе подойдет обычный int

2024-03-30 05:36 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +		for k, item := range lc.items {
Полный пробего по мапе происходит не за линейное время

2024-03-31 07:18 UTC, ErmakGit commented on hw04_lru_cache/list.go
> +	items     map[*ListItem]*ListItem
Мапу удалил, добавил параметр для подсчета количества элементов

2024-03-31 07:18 UTC, ErmakGit commented on hw04_lru_cache/list.go
> +	once      sync.Once
once удалил за ненадобностью

2024-03-31 07:41 UTC, ErmakGit commented on hw04_lru_cache/cache.go
> +		for k, item := range lc.items {
Исправил, теперь все операции удовлетворяют условию О(1)

2024-03-31 08:02 UTC, vladislavmass requested changes

2024-03-31 08:02 UTC, hungry-honeybadger commented on hw04_lru_cache/cache.go
> +	if len(lc.items) == lc.capacity {
Почему removeLast определяет должен он удалять или нет? Это решение относится скорее к методу Set, а removeLast должен  просто удалить последний элемент

2024-03-31 08:02 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	_, exist := lc.Get(key)
Из-за того, что после Get мы отпустили мьютекс, на момент когда мы мьютекс возьмем обратно результат Get может быть уже не актулен. Например мы в методе Get узнали что элемент в слайсе и сделали его первым, мьютекс отпустили, после этого соседний поток берет мьютекс  и тоже выполняет Get, он тоже нашел элемент и сделал его первым. Потом он вернул мьютекс но элемент который мы хотели править уже стал 2

2024-03-31 13:52 UTC, ErmakGit commented on hw04_lru_cache/cache.go
> +	if len(lc.items) == lc.capacity {
исправлено

2024-03-31 13:53 UTC, ErmakGit commented on hw04_lru_cache/cache.go
> +	_, exist := lc.Get(key)
Если я оборачиваю в Set мьютексами вызов Get, то тесты вылетают по тайм-ауту.
Я обернул только те части, в которых идет либо чтение, либо изменение очереди или словаря.

2024-03-31 18:02 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	_, exist := lc.Get(key)
Это ожидаемое поведение. Так как сет уже взял мьютекс и потом пошел вызов get. Get пытается получить мьютекс, но получить его можно только когда его отпустит сет. И поэтому у вас получается ситуация когда код завис на получение  лока в методе Get

2024-03-31 18:07 UTC, vladislavmass requested changes

2024-03-31 18:07 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	lc.mu.Lock()
Операция Get должна быть атомарна. Тоесть взяли лок, попробовали получить элемент, если нашли перенесли его в начало и только потом сняли лок

2024-03-31 18:07 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	_, exist := lc.Get(key)
В данном случае 2 решения. Либо дублировать часть кода метода Get в методе Set. Либо создать не экспортируемый метод get, перенести в него код метода Get без взятия лока. И вызывать его в методах Get и Set в которых и брать лок

2024-04-01 03:29 UTC, ErmakGit commented on hw04_lru_cache/cache.go
> +	_, exist := lc.Get(key)
Благодарю за помощь)

2024-04-01 04:45 UTC, vladislavmass approved these changes

2024-04-01 08:39 UTC, merged