HW05: implemented parallel execution
ErmakGit/otus-hws pull request #5
Opened 2024-04-01 08:42 UTC by ErmakGit

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-04-02 19:56 UTC, hungry-honeybadger requested changes
Хорошее начало, но код очень переусложнен и есть много потенциальных локов. Попробуйте реализовать следующий алгоритм.
1) При запуске Run создать небуферезированный канал для тасков и счетчик ошибок
2) Запустите воркеры. Воркер должен выполнять таск, а в случае возникновения ошибки сам воркер увеличивает счетчик.
3) Сделать цикл for по таскам. На каждом шаге проверяем не больше ли счетчик ошибок максимального колличчества, если счетчик больше то закрываем канал тасков и выходим из цикла

2024-04-02 19:56 UTC, hungry-honeybadger commented on hw05_parallel_execution/run.go
> +	select {
Этот блок селект не несет в себе никакой полезной нагрзуки

2024-04-02 19:56 UTC, hungry-honeybadger commented on hw05_parallel_execution/run.go
> +		atomic.AddInt64(&executeCount, 1)
Этот код синхронный, поэтому тут атомик не нужен

2024-04-02 19:56 UTC, hungry-honeybadger commented on hw05_parallel_execution/run.go
> +			atomic.AddInt64(&errorsCounter, 1)
Этот код синхронный, поэтому тут атомик не нужен

2024-04-02 19:56 UTC, hungry-honeybadger commented on hw05_parallel_execution/run.go
> +				stop <- struct{}{}
Вместо того, чтобы  отправлять пустую структуру проще просто закрыть канал

2024-04-02 19:56 UTC, hungry-honeybadger commented on hw05_parallel_execution/run.go
> +			results <- executed
В случае выхода по ошибке тут можно получить лок

2024-04-02 19:56 UTC, hungry-honeybadger commented on hw05_parallel_execution/run.go
> +		jobs <- task
Тут также можно словить лок.

2024-04-03 09:47 UTC, vladislavmass requested changes

2024-04-03 09:47 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +			close(jobs)
Тут явно про что-то забыли

2024-04-03 10:48 UTC, ErmakGit commented on hw05_parallel_execution/run.go
> +			close(jobs)
wg.Wait()
Просто рука-лицо)
Был опять-таки не прав, но исправился.

2024-04-03 13:01 UTC, vladislavmass approved these changes

2024-04-03 13:01 UTC, hungry-honeybadger commented on hw05_parallel_execution/run.go
> +			close(jobs)
Тут лучше было бы выйти только из цикла и пойти по основному пути. Таким образом у нас не было бы дублирование кода вида
```
close(jobs)
wg.Wait()
```
и шанс получить ошибку был бы ниже

2024-04-03 13:01 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +		errCounter.mu.RLock()
блок кода с 19 по 21 строку скорее лишний, чем полезный. Так как он усложняет код, но при этом не дает какой либо заметный результат

2024-04-03 13:01 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +			errCounter.mu.Lock()
Такие вещи лучше оформлять как методы структуры

2024-04-03 13:01 UTC, vladislavmass commented on hw05_parallel_execution/run.go
> +		errCounter.mu.RLock()
Такие вещи лучше оформлять как методы структуры

2024-04-07 07:27 UTC, vladislavmass approved these changes

2024-04-08 09:07 UTC, merged